name: Release package on GitHub
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Release on GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "publish -Pversion=${{ github.event.release.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
